### peticion al servidor
GET https://museo.blumbit.net/api/categoria
Authorization: Bearer 1|2qEQzrBCLVzHhjLM2vh2fPzvRJhOCwzp6eXv5TYb6aac5a7c


###
GET http://127.0.0.1:8000/api/categoria
Authorization: Bearer 1|FR4yb2Xv4V4rLfmqggn4EI5D7P4GVLZeDC2XpWlPfe3ea03a

### guardar categoria
POST https://museo.blumbit.net/api/categoria
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|FR4yb2Xv4V4rLfmqggn4EI5D7P4GVLZeDC2XpWlPfe3ea03a

{
    "nombre": "ARTE Y PINTURA"
}

### Mostrar
GET http://127.0.0.1:8000/api/categoria/2

### modificar
PUT http://127.0.0.1:8000/api/categoria/1
Accept: application/json
Content-Type: application/json

{
    "nombre": "ESCULTURA MODIFICADA",
    "estado": true
}
### eliminar
DELETE http://127.0.0.1:8000/api/categoria/2
Accept: application/json